services:
  app:
    build:
      context: .
    container_name: adaptive_st_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: bundle exec rails server -b 0.0.0.0

  sidekiq:
    build:
      context: .
    container_name: adaptive_st_sidekiq
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: bundle exec sidekiq

  trading_daemon:
    build:
      context: .
    container_name: adaptive_st_daemon
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: bundle exec rake trading:start


  postgres:
    image: postgres:17
    container_name: adaptive_st_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: adaptive_st_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  bundle_cache: